services:
  redis507:
    image: "redis:5.0.7"
    ports:
      - "6379:6379" 
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "3061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql" 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bluebell
    volumes:
      - ./init.sql:/data/application/init.sql
  bluebell_app:
    image: bluebell_app:latest
    build: .
    command: sh -c "./wait-for.sh redis507:6379 mysql8019:3306 -- ./bluebell_app ./config/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8081:8081"